### ISSUE TITLE
404 from links to /about

### ISSUE THREAD

**Issue by rzgry** [canosp/canosp.github.io#4]
Hello 👋

Noticed if you click on the `CANOSP` link on the home page or on an article page it points to https://canosp.ca/about/ which gives a 404 

<img src="https://user-images.githubusercontent.com/16768710/91490256-260c0000-e880-11ea-96a3-789b66901d20.png" width="400"> 

<img src="https://user-images.githubusercontent.com/16768710/91490507-8ac75a80-e880-11ea-879d-a3e413be5b53.png" width="400">

**Comment by gojeffcho** [comment]
Thank you for pointing this out!

I pushed a commit that fixes this on my end, and should update the author link from the main page as well as within the article pages.
